[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
journal_dapp = "4HRxGm7uKwqbDXz7Ywt8FeGtx7GovKMqUGQpEBtiWapc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
